# Generated by Django 5.2.8 on 2025-12-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
