# Generated by Django 5.2.1 on 2025-12-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
