# Generated by Django 5.2.1 on 2025-12-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
