# Generated by Django 5.2.1 on 2025-12-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedPost',
        ),
    ]
